export const theme = {
  colors: {
    primary: '#f6ac36',
    secondary: '#3071B2',
    success: '#4AA361',
    warning: '#CD5542',
    error: '#dc3545',
    info: '#17a2b8',
    light: '#f8f9fa',
    dark: '#343a40',
    white: '#ffffff',
    black: '#000000',
    gray: {
      100: '#f8f9fa',
      200: '#e9ecef',
      300: '#dee2e6',
      400: '#ced4da',
      500: '#adb5bd',
      600: '#6c757d',
      700: '#495057',
      800: '#343a40',
      900: '#212529',
    },
    text: {
      primary: '#212529',
      secondary: '#6c757d',
      muted: '#adb5bd',
      disabled: '#ced4da',
    },
    background: {
      primary: '#ffffff',
      secondary: '#f8f9fa',
      tertiary: '#e9ecef',
    },
    border: {
      light: '#dee2e6',
      medium: '#ced4da',
      dark: '#adb5bd',
    },
    status: {
      // 결제/배송/등록/취소/완료 등 주요 상태별 색상
      결제완료: { background: '#4AA361', color: '#fff' },
      결제대기: { background: '#CD5542', color: '#fff' },
      결제실패: { background: '#AAAAAA', color: '#fff' },
      환불진행: { background: '#F39C12', color: '#fff' },
      환불완료: { background: '#F39C12', color: '#fff' },
      배송준비: { background: '#000000', color: '#fff' },
      배송중: { background: '#3071B2', color: '#fff' },
      배송완료: { background: '#4AA361', color: '#fff' },
      배송취소: { background: '#c02626', color: '#fff' },
      신청완료: { background: '#ffb300', color: '#fff' },
      반납중: { background: '#6c757d', color: '#fff' },
      반납완료: { background: '#6c757d', color: '#fff' },
      등록완료: { background: '#4AA361', color: '#fff' },
      등록대기: { background: '#3071B2', color: '#fff' },
      계약종료: { background: '#CD5542', color: '#fff' },
      판매종료: { background: '#CD5542', color: '#fff' },
      취소: { background: '#AAAAAA', color: '#fff' },
      취소완료: { background: '#AAAAAA', color: '#fff' },
      대기: { background: '#3071B2', color: '#fff' },
      완료: { background: '#4AA361', color: '#fff' },
      오류: { background: '#dc3545', color: '#fff' },
      실패: { background: '#dc3545', color: '#fff' },
      기본: { background: '#6c757d', color: '#fff' },
    },
  },
  spacing: {
    xs: '4px',
    sm: '8px',
    md: '16px',
    lg: '24px',
    xl: '32px',
    xxl: '48px',
  },
  borderRadius: {
    sm: '4px',
    md: '8px',
    lg: '12px',
    xl: '16px',
    round: '50%',
  },
  typography: {
    fontFamily: {
      primary:
        'NanumSquareNeo, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      mono: 'Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    },
    fontSize: {
      xs: '12px',
      sm: '14px',
      md: '16px',
      lg: '18px',
      xl: '20px',
      xxl: '24px',
      xxxl: '32px',
    },
    fontWeight: {
      light: 300,
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      extrabold: 800,
    },
    lineHeight: {
      tight: 1.2,
      normal: 1.5,
      relaxed: 1.75,
    },
  },
  shadows: {
    sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
    md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
    lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
    xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
  },
  breakpoints: {
    xs: '480px',
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
    xxl: '1536px',
  },
  zIndex: {
    dropdown: 1000,
    sticky: 1020,
    fixed: 1030,
    modalBackdrop: 1040,
    modal: 1050,
    popover: 1060,
    tooltip: 1070,
  },
  transitions: {
    fast: '150ms ease-in-out',
    normal: '250ms ease-in-out',
    slow: '350ms ease-in-out',
  },
} as const;

export type Theme = typeof theme;
export type ColorKey = keyof typeof theme.colors;
export type SpacingKey = keyof typeof theme.spacing;
export type BorderRadiusKey = keyof typeof theme.borderRadius;
export type FontSizeKey = keyof typeof theme.typography.fontSize;
export type FontWeightKey = keyof typeof theme.typography.fontWeight;
